### ISSUE TITLE
binance does not have market symbol NEAT/ETH

### ISSUE THREAD

**Issue by SergenBey** [ShallowSmile1/Triangular-arbitrage-bot#1]
Hi bro, i look your project and this is a triangular or anything? because graphic so mixed...
and i have this problem. how can i solve?

![triangularerror](https://user-images.githubusercontent.com/114618571/192879173-fb784cbf-3316-4a97-8f23-c6197671d230.png)

**Comment by ShallowSmile1** [comment]
Hi. That's easily solved problem, it's happend becouse of trousble in mybuy.xml file. Everything you need to do is just replace all NEAT coin to NEAR. I just typo that NEAR name wrong in file. So when bot tying to analize it, he said that there isn't coin with name NEAT. You can fix it with yourself, or wait, i going to fix a couple of problems in next commit of proj))
upd: problem fixed)

**Comment by SergenBey** [comment]
Ah... Right.
Can you give me your WhatsApp or Telegram or any global contact app. ?
I have a few questions and i have a few idea.

**Comment by ShallowSmile1** [comment]
Yea. U can write me at Telegram: @shallowsmile
